services:
  bitwarden-to-keepass:
    build: .
    image: bitwarden-to-keepass:latest
    volumes:
      - ./exports:/exports
      - 'bw-config:/root/.config/Bitwarden CLI'
    env_file:
      - .env

volumes:
  bw-config:
